<?php
namespace Twitter\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeRepository extends EntityRepository
{
    public function followingCount($user_id){
        $q =  $this->getEntityManager()->createQueryBuilder();
        $q->select('count(l.user)');
        $q->where('l.user=:user');        
        $q->from('TwitterMainBundle:Like','l'); 
        $q->setParameter('user', $user_id);
        try {
            return $q->getQuery()->getSingleScalarResult();  ;
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }        
    }

    public function followersCount($user_id){
        $q = $this->getEntityManager()->createQueryBuilder();
        $q->select('count(l.userFollow)');
        $q->where('l.userFollow=:userFollow');
        $q->from('TwitterMainBundle:Like','l');
        $q->setParameter('userFollow', $user_id);        
        try {
            return $q->getQuery()->getSingleScalarResult();  ;
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }              
    }

}