<?php
namespace Twitter\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends EntityRepository
{


    public function findAllByIdJoinedToLike($user_id)
    {
        $query = $this->getEntityManager()
        ->createQuery('
            SELECT t FROM TwitterMainBundle:Like l
            LEFT JOIN TwitterMainBundle:Tweet t WITH l.user=t.user or t.user = :user_id
            WHERE l.userFollow = :user_id
            ORDER BY t.createdAt DESC
            '
        )->setParameter('user_id', $user_id);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }


}