Twitter\UserBundle\Entity\User:
    type:  entity
    repositoryClass: Twitter\UserBundle\Repository\UserRepository        
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO