Twitter\MainBundle\Entity\Like:
    type: entity
    table: like
    indexes:
        user_id:
            columns:
                - user_id
        user_id_follow:
            columns:
                - user_id_follow
    uniqueConstraints:
        user_id_user_id_follow:
            columns:
                - user_id
                - user_id_follow                
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        userFollow:
            targetEntity: Twitter\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id_follow:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Twitter\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
