parameters:
#    twitter_main.example.class: Twitter\MainBundle\Example

services:
#    twitter_main.example:
#        class: %twitter_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
