<?php
namespace Twitter\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function searchUserByName($username){
        $q = $this->getEntityManager()
        ->createQuery('
            SELECT u.usernameCanonical,u.username, u.id, l.id as likeid  FROM TwitterUserBundle:User u
            LEFT JOIN TwitterMainBundle:Like l WITH l.user=u.id
            WHERE u.usernameCanonical LIKE :username
            ')->setParameter('username', '%'.$username.'%');
        try {
            return $q->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }    
    }
}