<?php
namespace Twitter\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function searchUserByName($username){
        $qb = $this->createQueryBuilder('u');
        $qb ->select('u')
            ->where($qb->expr()->like('u.usernameCanonical', ':username'))
            ->setParameter('username', '%'.$username.'%');
        try {
            return $qb->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }  
    }
}